### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

1. Create a 1D array of numbers from 0 to 9

In [1]:
import numpy as np

In [2]:
num_x = np.arange(0,10)
num_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [3]:
mat= np.full((3,3),True)
mat

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [4]:
arr_1= np.arange(20,39)
arr_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38])

4. Replace all odd numbers in Q3 by -1

In [5]:
arr_1[arr_1%2 != 0] =-1
arr_1

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38])

5. Create two arrays of length 10 and print out  common items in both arrays

In [6]:
num_1 = np.arange(2,22,2)
num_2 = np.arange(1,11)

In [7]:
num_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
num_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
intersect_num= np.intersect1d(num_1,num_2)
intersect_num

array([ 2,  4,  6,  8, 10])

6.  Create a 5x5 identity matrix

In [10]:
matA = np.eye(5)
matA

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [11]:
x= np.array([10, 12, 9, 2, 20])
y= np.linspace(10,20,101)
z= np.ones((2,3))

print(f" x: {x} \n y: {y} \n z: {z}")

 x: [10 12  9  2 20] 
 y: [10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20. ] 
 z: [[1. 1. 1.]
 [1. 1. 1.]]


8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [12]:
arr_x = np.sort(x)
average = np.mean(arr_x)
st_deviation= np.std(arr_x)

print(f' Average: {average} and Standard deviationn: {round(st_deviation,2)}')

 Average: 10.6 and Standard deviationn: 5.78


9. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
arr_3 = np.random.randint(1,100,(10,10))
arr_3_min = np.min(arr_3)
arr_3_max = np.max(arr_3)

print(f" {arr_3} \n minimum: {arr_3_min} \n maximum: {arr_3_max}")

 [[ 1 69 30 30  7 73 39 17 99 52]
 [ 1 80 88 28 55 29 21 45  8 28]
 [39 71  6 17  5 43  7 79 10 63]
 [71 46 64 60  3 61 68 64 55 76]
 [51 42 23 71 24 52 68 62 86 70]
 [59 49  9 24 26 93 29 81 40 44]
 [39 85 10  2  4 98 82 27 11  4]
 [82  6 12 12 76 24 65 49 64 69]
 [29 21 50 34 57 71 72  8 30 96]
 [ 5 10 89 70 23  5  1 43 78 23]] 
 minimum: 1 
 maximum: 99


10. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
matB= np.arange(0,9).reshape((3,3))
mat_values = np.matrix(matB)
mat_values


matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [15]:
num = np.arange(1,7).reshape((2,3))
num

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [16]:
arr_value = np.linspace(0,10,5)
arr_value

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [17]:
numbers = np.zeros((3,3))
numbers

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [18]:
arr_inclusive = np.linspace(0.1,10,12,endpoint=True)
arr_inclusive

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10)

In [19]:
matrixx= np.full((5,7),10)
new_mat = np.matrix(matrixx)
new_mat

matrix([[10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

In [21]:
#Ans: Numpy can take multiple dimension but a list can take only one dimension

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [22]:
arr_one = np.ones(50,dtype= int)
for i in range(1,50,2):
    arr_one[i] = 0
    
arr_one

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [23]:
arr_10 = np.eye(10)
arr_10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [24]:
arr_zero = np.zeros((10,10))
np.fill_diagonal(arr_zero,1)

arr_zero

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [25]:
f= np.array([[1,2],[3,4]])
h= np.array([[5,6],[7,8]])

dot_product= np.dot(f,h)
dot_product

array([[19, 22],
       [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [26]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

a*b

array([[ 5, 12],
       [21, 32]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [27]:
c= np.array([[1,2],[3,4]])
d= 5

d*c

array([[ 5, 10],
       [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [28]:
A = np.array([[1,2],[3,4]])
B = np.transpose(A)

A*B

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [29]:
A= np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

multi1= A*B
multi2= B*A

print(f" multi1: {multi1} is the same as multi2: {multi2}")


 multi1: [[ 5 12]
 [21 32]] is the same as multi2: [[ 5 12]
 [21 32]]


25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [30]:
final_arr= np.array([[0, 1, 2], [3, 4, 5]])
A= final_arr[0]
B= final_arr[1]
C= final_arr[:,1]
D= final_arr[0,2]

print(A)
print(B)
print(C)
print(D)

[0 1 2]
[3 4 5]
[1 4]
2
